web/router.ex
defmodule Risen.Router do
  use Risen.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Risen.Landing do
    pipe_through :browser

    get   "/", HomeController, :index

    get   "/schools", SchoolsController, :index

    get   "/signin", AccountController, :signin_get
    post  "/signin", AccountController, :signin_post

    get   "/signout", AccountController, :signout_get
  end

  scope "/a", Risen.Admin, as: :admin do
    pipe_through :browser

    get   "/", IndexController, :index

    get   "/students", StudentsController, :index
    get   "/students/:id/edit", StudentsController, :edit
    patch "/students/:id/edit", StudentsController, :update

    get    "/employers", EmployersController, :index

    get    "/schools", SchoolsController, :index
    get    "/schools/new", SchoolsController, :new
    post   "/schools", SchoolsController, :create
    get    "/schools/:id/edit", SchoolsController, :edit
    patch  "/schools/:id", SchoolsController, :update
    delete "/schools/:id", SchoolsController, :delete

    get   "/batches", BatchesController, :index
    get   "/batches/:id", BatchesController, :show
    patch "/batches/:id", BatchesController, :update

    get    "/majors", MajorsController, :index
    get    "/majors/new", MajorsController, :new
    post   "/majors", MajorsController, :create
    get    "/majors/:id/edit", MajorsController, :edit
    patch  "/majors/:id", MajorsController, :update
    delete "/majors/:id", MajorsController, :delete
  end

  scope "/e", Risen.Employer, as: :employer do
    pipe_through :browser

    get   "/", IndexController, :index

    get   "/register", RegisterController, :new
    post  "/register", RegisterController, :create

    get   "/:employer_slug/setup", SetupController, :edit
    patch "/:employer_slug/setup", SetupController, :update

    get   "/:employer_slug/students/:id", StudentsController, :show
    patch "/:employer_slug/students/:id", StudentsController, :update

    get   "/:employer_slug/batches", BatchesController, :index
    get   "/:employer_slug/batches/:id", BatchesController, :show

    get   "/:employer_slug/settings", SettingsController, :show
    patch "/:employer_slug/settings", SettingsController, :update
  end

  scope "/s", Risen.Student, as: :student do
    pipe_through :browser

    get   "/:school_slug/register", RegisterController, :new
    post  "/:school_slug/register", RegisterController, :create

    get   "/:school_slug/:id/setup", SetupController, :edit
    patch "/:school_slug/:id/setup", SetupController, :update
    get   "/:school_slug/:id/done", SetupController, :done

    get   "/:id/edit", ProfileController, :edit
    patch "/:id/edit", ProfileController, :update
  end

end

web/views/shared_view.ex
defmodule Risen.SharedView do
  use Risen.Web, :view
end

web/templates/shared/admin_app_menu.html.eex
<div class="adminAppMenu js-menu drawer">
  <div class="drawer-content">
    <ul class="navMenu">
      <li><a class="u-noDecor" href="<%= admin_students_path(@conn, :index) %>">Students</a></li>
      <li><a class="u-noDecor" href="<%= admin_batches_path(@conn, :index) %>">Batches</a></li>
      <li><a class="u-noDecor" href="<%= admin_employers_path(@conn, :index) %>">Employers</a></li>
      <li><a class="u-noDecor" href="<%= admin_schools_path(@conn, :index) %>">Schools</a></li>
      <li><a class="u-noDecor" href="<%= admin_majors_path(@conn, :index) %>">Majors</a></li>
    </ul>
  </div>
  <div class="drawer-footer">
    <a class="btn btn--short btn--dark--o" href="<%= account_path(@conn, :signout_get) %>">Sign Out</a>
  </div>
</div>

web/templates/shared/admin_topbar.html.eex
<div class="topBar topBar--mobile">
  <a href="<%= admin_students_path(@conn, :index) %>" class="logo logo--streamlined"></a>
  <div class="appBarMenu">
    <ul class="appBarMenu-list">
      <li class="appBarMenu-list-item">
        <a class="appBarMenu-link" href="<%= admin_students_path(@conn, :index) %>">Students</a>
      </li>
      <li class="appBarMenu-list-item">
        <a class="appBarMenu-link" href="<%= admin_batches_path(@conn, :index) %>">Batches</a>
      </li>
      <li class="appBarMenu-list-item">
        <a class="appBarMenu-link" href="<%= admin_employers_path(@conn, :index) %>">Employers</a>
      </li>
      <li class="appBarMenu-list-item">
        <a class="appBarMenu-link" href="<%= admin_schools_path(@conn, :index) %>">Schools</a>
      </li>
      <li class="appBarMenu-list-item">
        <a class="appBarMenu-link" href="<%= admin_majors_path(@conn, :index) %>">Majors</a>
      </li>
    </ul>
  </div>
  <%=
    render Risen.SharedView,
    "top_bar_user.html",
    conn: @conn,
    image_url: "http://placehold.it/150x150"
  %>
  <!-- 2nd Pass: Make menu an SVG -->
  <div class="menuIcon js-trigger">
    <div class="menuIcon-stripe"></div>
    <div class="menuIcon-stripe"></div>
    <div class="menuIcon-stripe"></div>
  </div>
</div>

web/templates/shared/batch_item.html.eex
<div class="batch card no-hover">
  <h2 class="card-title"><a class="u-noDecor" href="<%= @href %>"><%= @title %></a></h2>
  <div class="card-content">
    <div class="studentPicsWrapper">
      <ul class="studentPics">
        <%= for student <- @batch.students do %>
        <li><img class="pic pic--student--sm u-round" src="<%= Risen.StudentPic.url({student.pic, student}) %>" /></li>
        <% end %>
      </ul>
    </div>
    <div class="filler"></div>
    <div class="studentCount">
      <p><%= length(@batch.students) %> <%= Inflex.inflect("Student", length(@batch.students)) %></p>
    </div>
  </div>
</div>


<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function() {

    // NOTE: I don't think this is efficient because the event listeners are ran
    //   and the functions are declared multiple times if multiple batch_item are
    //   rendered in a page.
    // NOTE: On the 2nd pass, we can at least extract checkBatchPics()
    var batches = document.querySelectorAll('.batch');
    for (var i = 0; i < batches.length; i++) {
      checkBatchPics(batches[i]);
    }

    function checkBatchPics(batch) {
      var w = batch.querySelector('.studentPicsWrapper'),
          s = batch.querySelector('.studentPics'),
          inners = batch.querySelectorAll('.studentPics li'),
          wWidth = undefined, sWidth = undefined, switchPoint = undefined;

      function checkFlex() {
        sWidth = s.clientWidth;
        wWidth = w.clientWidth;
        if (switchPoint !== undefined && sWidth - 1 - 1 >= switchPoint) {
          // Remove flex
          s.classList.remove('flex');
          for (var i = 0; i < inners.length; i++) {
            inners[i].classList.remove('flex');
          }
          switchPoint = undefined;
        }
        else if (wWidth === sWidth) {
          // Add flex
          s.classList.add('flex');
          for (var i = 0; i < inners.length; i++) {
            inners[i].classList.add('flex');
          }
          switchPoint = switchPoint === undefined ? sWidth : switchPoint;
        }
      }

      checkFlex();
      window.addEventListener('resize', checkFlex);
    }
  });
</script>

web/templates/shared/employer_app_menu.html.eex
<div class="drawer js-menu employerAppMenu">
  <div class="drawer-content">
    <ul class="navMenu">
      <li>
        <a class="u-noDecor" href="<%= employer_batches_path(@conn, :index, @employer.slug) %>">Batches</a>
      </li>
      <li>
        <a class="u-noDecor" href="<%= employer_settings_path(@conn, :show, @employer.slug) %>">Settings</a>
      </li>
    </ul>
  </div>
  <div class="drawer-footer">
    <p>You are signed in to manage <strong><%= @employer.name %></strong>.</p>
    <a class="btn btn--short btn--o" href="<%= account_path(@conn, :signout_get) %>">Sign Out</a>
  </div>
</div>

web/templates/shared/employer_signup.html.eex
<div class="sign-up">
  <div class="logo">
    <h1>RISEN</h1>
    <p>Sign-up with us</p>
  </div>
  <form action="">
    <p><input name="organization" type="text" placeholder="Organization Name"></p>
    <p><input name="email" type="email" placeholder="Email"></p>
    <p><input name="password" type="password" placeholder="Password"></p>
    <input name="submit" type="submit" value="Create Account">
  </form>
</div>

web/templates/shared/employer_summary.html.eex
<div class="employerSummary">
<img class="employerSummary-pic pic pic--student--sm u-round" src="<%= Risen.EmployerLogo.url({@employer.logo, @employer}) %>" />
<div class="employerSummary-info">
  <h2 class="employerSummary-info-name"><%= @employer.name %></h2>
  <p class="employerSummary-info-studentCount"><%= length(@employer_students) %> <%= Inflex.inflect("Student", length(@employer_students)) %></p>
</div>

web/templates/shared/employer_topbar.html.eex
<div class="topBar topBar--mobile">
  <a href="<%= employer_batches_path(@conn, :index, @employer.slug) %>" class="logo logo--streamlined"></a>
  <div class="appBarMenu">
    <ul class="appBarMenu-list">
      <li class="appBarMenu-list-item">
        <a class="appBarMenu-link" href="<%= employer_batches_path(@conn, :index, @employer.slug) %>">Batches</a>
      </li>
      <li class="appBarMenu-list-item">
        <a class="appBarMenu-link" href="<%= employer_settings_path(@conn, :show, @employer.slug) %>">Settings</a>
      </li>
    </ul>
  </div>

  <%=
    render Risen.SharedView,
    "top_bar_user.html",
    conn: @conn,
    image_url: Risen.EmployerLogo.url({@employer.logo, @employer})
  %>

  <!-- 2nd Pass: Make menu an SVG -->
  <div class="menuIcon js-trigger">
    <div class="menuIcon-stripe"></div>
    <div class="menuIcon-stripe"></div>
    <div class="menuIcon-stripe"></div>
  </div>
</div>

web/templates/shared/form_errors.html.eex
<%= if @errors != [] do %>
  <div class="form-error">
    <div class="form-error__title">
      Oops, something went wrong:
    </div>
    <ul class="form-error__list">
      <%= for {attr, message} <- @errors do %>
        <li class="form-error__item"><%= attr %> <%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

web/templates/shared/signin_form.html.eex
<div class="signInForm container container--mobile">
  <a href="<%= home_path(@conn, :index) %>" class="logo"></a>
  <h2>Sign-in to your Risen account</h2>
  <div class="container--form">
    <form action="<%= account_path(@conn, :signin_post) %>" method="post">
      <%= render Risen.SharedView, "form_errors.html", errors: @errors %>
      <input type="hidden" name="_csrf_token" value="<%= get_csrf_token() %>">
      <input name="email" class="input-default" type="email" placeholder="Email" value="<%= if @conn.params["email"], do: @conn.params["email"], else: "" %>">
      <input name="password" class="input-default" type="password" placeholder="Password">
      <input name="submit" class="btn btn--short" type="submit" value="Sign In">
    </form>
  </div>
</div>

web/templates/shared/student_list_item.html.eex
<div class="student-list-item card">
    <div class="card-content">
        <div class="pic-container">
            <div class="student-pic-sm round-pic">
                <!-- static_path errors out: assign @conn not available in eex template. -->
                <!-- When connected, change # to = -->
                <img src="<%# static_path(@conn, "/images/ic_face_black_48dp_1x.png") %>">
            </div>
        </div>
        <div class="student-info-container">
            <p class="row">
                <span class="student-name">Sam Smith</span>
                <i class="status-badge neutral">Pending</i>
            </p>
            <p class="row">
                <span class="school-name">Pensacola Christian College</span>
                <span class="middot"></span>
                <span class="student-major">Computer Science</span>
            </p>
        </div>
        <div class="date-info-container">
            <p class="row">Sent on</p>
            <p class="row">January 4, 2016</p>
        </div>
    </div>
</div>

web/templates/shared/student_settings.html.eex
<div class=studentSettings>

  <div class="container--form">
    <%= form_for @changeset, @action, [multipart: true, method: "patch"], fn f -> %>

      <%= render Risen.SharedView, "form_errors.html", errors: f.errors %>

      <h3>Photo</h3>
      <div class="picChooser">
        <img class="picChooser-pic u-round" src="<%= Risen.StudentPic.url({@student.pic, @student}) %>"></img>
        <label for="file-upload" class="picChooser-btn btn btn--xshort" type="file"><%= if @edit do %>Change<% else %>Choose<% end %>...</label>
        <input id="file-upload" name="pic" class="picChooser-file" type="file" accept=".jpg,.jpeg,.png">
      </div>

      <div class="resumeUploader">
        <p class="resumeUploader-attached"><%= if @student.resume do %><%= @student.resume %> attached<% end %></p>
        <label for="resume-upload" class="resumeUploader-btn" type="file"><h2>Upload <%= if @edit do %>New<% end %> PDF Resume...</h2></label>
        <input id="resume-upload" name="resume" class="resumeUploader-file" type="file" accept=".pdf">
      </div>

      <label for="major">
        <h3>Major</h3>
        <%= unless @student.major_id do %>
        <label class="singleSelect">
          <%= select(f, :major_id, Enum.map(@majors, fn(m) -> {m.name, m.id} end), id: "major", class: "input-default input-default--black", prompt: "Select Major", required: true) %>
        </label>
        <% else %>
        <label class="singleSelect">
          <%= select(f, :major_id, Enum.map(@majors, fn(m) -> {m.name, m.id} end), id: "major", class: "input-default input-default--black", disabled: true) %>
        </label>
        <% end %>
      </label>

      <label for="role">
        <h3>Ideal Role</h3>
        <%= text_input f, :ideal_role, id: "role", class: "input-default input-default--black", placeholder: "Type your ideal role...", required: false %>
      </label>

      <label for="job-type">
        <h3>Job Type</h3>
        <label class="singleSelect">
          <%= select(f, :job_type, Risen.Student.job_types, id: "job-type", class: "input-default input-default--black", prompt: "Select Job Type", required: true) %>
        </label>
      </label>

      <label for="visa-status">
        <h3>Visa Status</h3>
        <label class="singleSelect">
          <%= select(f, :visa_status, Risen.Student.visa_statuses, id: "visa-status", class: "input-default input-default--black", prompt: "Select Visa Status", required: true) %>
        </label>
      </label>

      <label for="location-pref">
        <h3>Location Preference</h3>
        <%= text_input f, :location_preference, id: "location-pref", class: "input-default input-default--black", placeholder: "Type your location preference...", required: true %>
      </label>

      <div class="checkbox">
        <%= checkbox f, :is_willing_to_relocate, id: "relocate", class: "inputCheckbox" %>
        <label for="relocate"><div></div>I'm willing to relocate</label>
      </div>

      <input type="submit" class="btn btn--short btn--dark" value="Save">

    <% end %>
  </div>

</div>


<script type="text/javascript">
  // NOTE: This function probably needs to go in /web/static/js/utils.js and imported in app.js
  function previewImage(input, targetSelector) {
    if (input.files && input.files[0]) {
      // NOTE: FilReader API is supported in IE10+
      var reader = new FileReader();
      reader.readAsDataURL(input.files[0]);
      reader.onload = function(e) {
        document.querySelector(targetSelector).src = e.target.result;
      }
    }
  }

  document.addEventListener('DOMContentLoaded', function() {
    var picUploader = document.querySelector('.picChooser-file'),
        resumeUploader = document.querySelector('.resumeUploader-file');

    // Preview the selected image
    picUploader.onchange = function() { previewImage(picUploader, '.picChooser-pic'); };

    // Print PDF name when selected
    resumeUploader.onchange = function() {
      var fileName = resumeUploader.value.split('\\').pop();
      document.querySelector('.resumeUploader-attached').innerHTML = fileName + " attached";
    };
  });
</script>

web/templates/shared/student_signup.html.eex
<div class="sign-up">
  <div class="logo">
    <h1>RISEN</h1>
    <p>Sign-up with us through</p>
    <img class="school-pic" src="">
    <p>School Name</p>
  </div>
  <form action="">
    <p><input name="organization" type="email" placeholder="Full Name"></p>
    <p><input name="email" type="text" placeholder="Email"></p>
    <p><input name="password" type="password" placeholder="Password"></p>
    <input name="submit" type="submit" value="Sign Up">
  </form>
</div>

web/templates/shared/student_summary.html.eex
<div class="studentSummary">
  <img class="studentSummary-pic round-pic" src="<%= Risen.StudentPic.url({@student.pic, @student}) %>" />
  <div class="studentSummary-info">
    <p class="studentSummary-info-name"><%= @student.name %></p>
    <div class="studentSummary-info-meta">
      <span class="studentSummary-info-meta-school"><%= @student.school.name %></span>
      <span class="studentSummary-info-meta-major"><%= @student.major.name %></span>
    </div>
  </div>
</div>

web/templates/shared/topbar.html.eex
<div class="topBar topBar--mobile">
  <div class="logo logo--streamlined"></div>
  <!-- 2nd Pass: Make menu an SVG -->
  <div class="menuIcon js-trigger">
    <div class="menuIcon-stripe"></div>
    <div class="menuIcon-stripe"></div>
    <div class="menuIcon-stripe"></div>
  </div>
</div>


<script>
  document.addEventListener('DOMContentLoaded', function() {
    var menu = document.querySelector('.js-menu');
    // Prevent propagation pass menu
    menu.addEventListener('click', function(e) {
      e.stopPropagation();
    });
    // Toggle employer app menu
    document.querySelector('.menuIcon.js-trigger').addEventListener('click', function(e) {
      e.stopPropagation();
      menu.classList.toggle('is-in');
    });
    // Click outside to exit app menu
    document.querySelector('main').addEventListener('click', function(e) {
      menu.classList.remove('is-in');
    });
  });
</script>